# Generated by Django 4.2.7 on 2023-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_director_best_director_data_director_filmcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='best',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Лучшие фильмы'),
        ),
        migrations.AddField(
            model_name='actor',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='actor',
            name='filmcount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего фильмов'),
        ),
    ]
